graph TD
  A[Attacker] -->|Small spoofed query| B[Open DNS Resolver]
  B --> |Large DNS response| C[Victim]
  B1[Open DNS Resolver] -->|Large DNS response| C
  B2[Open DNS Resolver] -->|Large DNS response| C
  B3[Open DNS Resolver] -->|Large DNS response| C
