graph LR;
    A["etc/shadow"];
    B[Username];
    C["Encrypted Password"];
    D["Last Change"];
    E["Min Age"];
    F["Max Age"];
    G[Warning];
    H[Inactive];
    I[Expire];
    
    A --> B;
    A --> C;
    A --> D;
    A --> E;
    A --> F;
    A --> G;
    A --> H;
    A --> I;
    
    style A fill:#ff9966,stroke:#333,stroke-width:2px;
