classDiagram
    class Client
    class Context
    class AbstractExpression {
        +interpret(context: Context): void
    }
    class TerminalExpression {
        +interpret(context: Context): void
    }
    class NonterminalExpression {
        +interpret(context: Context): void
    }
    Client --> Context
    Client --> AbstractExpression
    AbstractExpression <|-- TerminalExpression
    AbstractExpression <|-- NonterminalExpression
    NonterminalExpression o-- AbstractExpression