mindmap
  root((Syntax))
    Keywords
      fn
      let
      use
    Identifiers
      Variables
      Functions
      Types
    Expressions
      Operators
      Function calls
      Blocks
    Statements
      Declarations
      Assignments
      Control flow