mindmap
  root((Common Traits))
    Display
      String formatting
      User output
    Debug
      Development output
      Debugging
    Clone
      Value duplication
      Deep copy
    Copy
      Stack-only data
      Implicit copies
    Default
      Default values
      Initialization