graph TB
subgraph "Master-Slave"
M[Master] -->|Write| S1[Slave 1]
M -->|Write| S2[Slave 2]
C1[Client] -->|Read| S1
C2[Client] -->|Read| S2
C3[Client] -->|Write| M
end
subgraph "Master-Master"
M1[Master 1] <-->|Sync| M2[Master 2]
C4[Client] -->|R/W| M1
C5[Client] -->|R/W| M2
end
