mindmap
    root((DevOps Tools))
        Source Control
            Git
            GitHub
        CI/CD
            Jenkins
            GitLab
        Infrastructure
            Terraform
            Ansible
        Containers
            Docker
            Kubernetes