mindmap
    root((Frameworks))
        Testing
            Selenium
            PyTest
        Deployment
            Fabric
            Capistrano
        Configuration
            Ansible
            Puppet