mindmap
    root((Management))
        Version Control
            Git
            SVN
        Documentation
            Inline
            External
        Testing
            Unit
            Integration