graph BT
    A[main.c] --> B[main.o]
    C[config.h] --> B
    D[utils.h] --> B
    E[utils.c] --> F[utils.o]
    D --> F
    C --> F
    G[lib.c] --> H[lib.o]
    I[lib.h] --> H
    B --> J[program]
    F --> J
    H --> J
