mindmap
    root["Instructions"]
        Build-time
            FROM
            COPY
            RUN
            ARG
        Runtime
            ENV
            EXPOSE
            CMD
            ENTRYPOINT