[processor.make]
exclude_paths = ["Makefile"]

[processor.spellcheck]
use_words_file = true

[processor.jsonlint]
enabled = false

[processor.ascii_check]
enabled = false

[processor.rumdl]
enabled = false

[processor.pandoc]
enabled = false

[processor.a2x]
enabled = false
