[processor.make]
exclude_paths = ["Makefile"]

[processor.tera]
extra_inputs = [
    "config/project.lua",
    "config/personal.lua",
    "config/version.lua",
    "config/python.lua",
    "config/github.lua",
    "config/shared.lua",
]

[processor.jsonlint]
enabled = false

[processor.ascii_check]
enabled = false

[processor.rumdl]
enabled = false

[processor.pandoc]
enabled = false

[processor.a2x]
enabled = false

[processor.luacheck]
enabled = false

[processor.script_check]
enabled = true
checker = "python"
args = ["scripts/md_lint.py", "-q"]
extensions = [".md"]
scan_dir = "marp"
