[processor.tera]
extra_inputs = [
    "config/project.lua",
    "config/personal.lua",
]

[processor.script.md_lint]
linter = "python"
args = ["scripts/md_lint.py", "-q"]
extensions = [".md"]
scan_dirs = ["marp"]

[processor.script.check_code_labels]
linter = "python"
args = ["scripts/check_code_labels.py", "-q"]
extensions = [".md"]
scan_dirs = ["marp"]

[processor.marp]
formats = [ "pdf" ]
max_jobs = 10
output_dir = "_site/marp"

[processor.pylint]
scan_dirs = ["scripts"]

[processor.markdownlint]
scan_dirs = ["marp"]

[processor.aspell]
scan_dirs = ["marp"]

[processor.zspell]
scan_dirs = ["marp"]

[processor.pdfunite]
output_dir = "_site/pdfunite"
source_output_dir = "_site/marp"

[processor.explicit]
command = "scripts/build_index.py"
inputs = [
    "resources/courses_index.html",
    "resources/courses_index.css",
    "resources/courses_index.js",
]
input_globs = [
    "_site/courses/**/*.pdf",
    "_site/pdfunite/**/*.pdf",
]
outputs = [
    "_site/index.html",
]
