graph TD
    subgraph "Redis Cluster"
        Node1[Node 1<br>Shards A,B]
        Node2[Node 2<br>Shards C,D]
        Node3[Node 3<br>Shards E,F]
    end

    Node1 --> Backup1[Persistence<br>For Shards A,B]
    Node2 --> Backup2[Persistence<br>For Shards C,D]
    Node3 --> Backup3[Persistence<br>For Shards E,F]