graph TD;
    A[Trust Setup];
    B[Host Based];
    C[User Based];
    D["etc/hosts.equiv"];
    E["~/.rhosts"];

    A --> B;
    A --> C;
    B --> D;
    C --> E;

    style A fill:#ff9966,stroke:#333,stroke-width:2px;
