graph LR;
    A[Variable Types];
    B[Local];
    C[Environment];
    D["name=value"];
    E["export name=value"];

    A --> B;
    A --> C;
    B --> D;
    C --> E;

    style A fill:#ff9966,stroke:#333,stroke-width:2px;
