graph TD;
    A[Login Shell];
    B["etc/profile"];
    C["~/.profile"];
    D["etc/bash.bashrc"];
    E["~/.bashrc"];

    A --> B;
    B --> C;
    A --> D;
    D --> E;

    style A fill:#ff9966,stroke:#333,stroke-width:2px;
