mindmap
    root["Getting Started"]
        Commands
            Learn basic commands
            Use --help
            Practice frequently
        Images
            Use official images
            Understand tags
            Check documentation
        Containers
            Name containers
            Remove unused
            Monitor resources