mindmap
    root((Serverless))
        Functions
            Lambda
            Azure Functions
        Services
            Managed
            Scalable
        Benefits
            Cost
            Scale