mindmap
    root((Kubernetes))
        Workloads
            Pods
            Deployments
        Services
            LoadBalancer
            Ingress
        Storage
            Volumes
            Claims