mindmap
    root((Scaling))
        Horizontal
            Instances
            Load Balance
        Vertical
            Resources
            Capacity
        Auto
            Demand
            Schedule