timeline
    title Evolution of Containerization
    1979 : Unix V7 : chroot introduced
    2000 : FreeBSD : Jails
    2004 : Solaris : Zones
    2008 : LXC : Linux Containers
    2013 : Docker : Initial Release
    2015 : Docker : Industry Standard
    2023 : Docker : Modern Architecture