mindmap
    root((ML Ops))
        Training
            Data
            Models
        Deployment
            Testing
            Production
        Monitoring
            Performance
            Drift