graph TD;
    A[find];
    B[Name];
    C[Type];
    D[Size];
    E[Time];
    F["-name *.txt"];
    G["-type f/d"];
    H["-size +100M"];
    I["-mtime -7"];

    A --> B;
    A --> C;
    A --> D;
    A --> E;
    B --> F;
    C --> G;
    D --> H;
    E --> I;

    style A fill:#ff9966,stroke:#333,stroke-width:2px;
