graph LR
    Client[Client] --> APIGateway[API Gateway]
    APIGateway --> Function1[Function 1]
    APIGateway --> Function2[Function 2]
    APIGateway --> Function3[Function 3]
    Function1 --> Database[Database]
    Function2 --> MessageQueue[Message Queue]
    Function3 --> ObjectStorage[Object Storage]