graph LR
    Publisher1[Publisher 1] --> MessageBroker[Message Broker]
    Publisher2[Publisher 2] --> MessageBroker
    MessageBroker --> Subscriber1[Subscriber 1]
    MessageBroker --> Subscriber2[Subscriber 2]
    MessageBroker --> Subscriber3[Subscriber 3]