timeline
    2008 : Azure Announced
    2010 : General Availability
    2014 : Microsoft Azure Rebranding
    2016 : Azure Resource Manager
    2018 : Azure Kubernetes Service
    2020 : Industry Solutions