mindmap
    root["Dockerfile"]
        Instructions
            Base Instructions
            Execution Instructions
            File Instructions
            Configuration Instructions
        Arguments
            Build Arguments
            Environment Variables
            Command Arguments
        Features
            Comments
            Variables
            Heredocs