mindmap
    root["LABEL"]
        Maintainer
            Contact info
            Organization
        Version
            Release
            Build number
        Environment
            Stage
            Purpose
        Documentation
            Description
            Usage