sequenceDiagram
    participant Client
    participant Redis

    Client->>Redis: HSET user:1000 username "john" email "john@example.com" visits 0
    Redis->>Client: (integer) 3

    Client->>Redis: HINCRBY user:1000 visits 1
    Redis->>Client: (integer) 1

    Client->>Redis: HGETALL user:1000
    Redis->>Client: 1) "username" 2) "john" 3) "email" 4) "john@example.com" 5) "visits" 6) "1"

    Client->>Redis: HMGET user:1000 username email
    Redis->>Client: 1) "john" 2) "john@example.com"