mindmap
  root((Scalar Types))
    Integers
      Signed(i8..i128)
      Unsigned(u8..u128)
    Floating-Point
      f32
      f64
    Boolean
      true
      false
    Character
      Unicode
      4 bytes