mindmap
  root((DevOps Tools))
    Source Control
      Git
      SVN
      Mercurial
    CI/CD
      Jenkins
      GitLab CI
      GitHub Actions
      CircleCI
      ArgoCD
    IaC
      Terraform
      Ansible
      CloudFormation
      Pulumi
    Containers
      Docker
      Kubernetes
      Helm
    Monitoring
      Prometheus
      Grafana
      ELK Stack
      Datadog
    Security
      SonarQube
      Snyk
      OWASP