graph TD
    IAC[Infrastructure as Code]
    IAC --> PROV[Provisioning]
    IAC --> CONFIG[Configuration]
    IAC --> ORCH[Orchestration]
    PROV --> TF[Terraform / OpenTofu]
    PROV --> PULUMI[Pulumi]
    PROV --> CFN[CloudFormation]
    CONFIG --> ANS[Ansible]
    CONFIG --> CHEF[Chef / Puppet]
    ORCH --> K8S[Kubernetes Manifests]
    ORCH --> HELM[Helm Charts]
