packages=[
    "unoconv",
    "python3-uno",
    "markdown",
    "asciidoc",
    "asciidoc-dblatex",
    "libreoffice",
    "pandoc",
    "lacheck",
    "latex2html",
    "sketch",
    "tidy",
    "texlive",
    "texlive-latex-base",
    "texlive-latex-extra",
    "texlive-binaries",
    "texlive-pictures",
    "texlive-pstricks",
    "texlive-luatex",
    "texlive-plain-generic",
    "ghostscript",
    "qpdf",
    "poppler-utils",
    "virtualenvwrapper",
]

packages_docs = [
    "sketch-doc",
]
