graph TD
    Node1[Node 1]
    Node2[Node 2]
    Node3[Node 3]
    Node4[Node 4]

    Node1 --Message Passing--> Node2
    Node1 --Message Passing--> Node3
    Node1 --Message Passing--> Node4
    Node2 --Message Passing--> Node3
    Node2 --Message Passing--> Node4
    Node3 --Message Passing--> Node4