mindmap
    root[Information Tools]
        /proc filesystem
            fd
            net
        netstat
            connections
            statistics
        ip
            addr
            link
        ss
            sockets
            stats