mindmap
    root[Configuration Tools]
        ifconfig
            interface config
            statistics
        ip
            modern tool
            replacement
        ifup/ifdown
            interface scripts
        route
            routing table
        iwconfig
            wireless