graph TB
BB[(Blackboard)] --> C[Control]
C --> KS1[Knowledge Source 1]
C --> KS2[Knowledge Source 2]
C --> KS3[Knowledge Source 3]
C --> KS4[Knowledge Source 4]
KS1 <--> BB
KS2 <--> BB
KS3 <--> BB
KS4 <--> BB
BB -.->|Solution State| S[Solution]
