graph TD
    Any --> AnyVal
    Any --> AnyRef
    AnyVal --> Unit
    AnyVal --> Boolean
    AnyVal --> Number
    Number --> Int
    Number --> Long
    Number --> Double
    Number --> Float
    AnyRef --> String
    AnyRef --> List
    AnyRef --> Option
    Null --> AnyRef
    Nothing --> Null
    Nothing --> AnyVal