graph TD
    Traversable --> Iterable
    Iterable --> Seq
    Iterable --> Set
    Iterable --> Map
    Seq --> IndexedSeq
    Seq --> LinearSeq
    IndexedSeq --> Vector
    IndexedSeq --> Array
    LinearSeq --> List
    LinearSeq --> Stream