graph TD
    Collection --> Access
    Collection --> Insert
    Collection --> Delete
    Access --> RandomAccess
    Access --> SequentialAccess
    Insert --> Head
    Insert --> Tail
    Insert --> Middle
    Delete --> FromHead
    Delete --> FromTail
    Delete --> FromMiddle