graph TD
    ErrorHandling --> TryObject
    ErrorHandling --> Either
    ErrorHandling --> Option
    TryObject --> Success
    TryObject --> Failure
    Either --> Left
    Either --> Right
    Option --> Some
    Option --> None