graph TD
    OOP --> Classes
    OOP --> Objects
    OOP --> Traits
    Classes --> CaseClasses
    Objects --> CompanionObjects
    Objects --> Singleton
    Traits --> Interface
    Traits --> Mixins