graph TD
    BD[Business Domain] --> SD1[Subdomain: Orders]
    BD --> SD2[Subdomain: Payments]
    BD --> SD3[Subdomain: Inventory]
    BD --> SD4[Subdomain: Shipping]
    SD1 --> MS1[Order Service]
    SD2 --> MS2[Payment Service]
    SD3 --> MS3[Inventory Service]
    SD4 --> MS4[Shipping Service]
