stateDiagram-v2
    [*] --> CLOSED
    CLOSED --> SYN_SENT
    CLOSED --> LISTEN
    SYN_SENT --> ESTABLISHED
    LISTEN --> SYN_RCVD
    SYN_RCVD --> ESTABLISHED
    ESTABLISHED --> FIN_WAIT_1
    ESTABLISHED --> CLOSE_WAIT