mindmap
  root((Performance))
    Vector
      Amortized O1 push
      On insertion
      O1 pop
    HashMap
      O1 average lookup
      Hash collisions
      Memory overhead
    String
      UTF-8 encoding
      On concatenation
      Memory reallocation
