graph TD
    BackupMethods[Backup Methods] --> RDB[RDB Snapshot]
    BackupMethods --> AOF[AOF Backup]
    BackupMethods --> Both[RDB + AOF]

    RDB --> AutoRDB[Automatic<br>via redis.conf]
    RDB --> ManualRDB[Manual<br>SAVE/BGSAVE]

    AOF --> CopyAOF[Copy AOF File]

    Both --> HybridBackup[Hybrid Backup]

    AutoRDB --> Copy[Copy Files<br>Offsite]
    ManualRDB --> Copy
    CopyAOF --> Copy
    HybridBackup --> Copy