graph TD
    A[Redundancy] --> B[LRS]
    A --> C[ZRS]
    A --> D[GRS]
    A --> E[GZRS]
    B[LRS/Locally Redundant]
    C[ZRS/Zone Redundant]
    D[GRS/Geo Redundant]
    E[GZRS/Geo-Zone Redundant]