mindmap
    root((Automation))
        Build
            Maven
            Gradle
        Deploy
            Ansible
            Terraform
        Test
            Selenium
            JUnit
        Monitor
            Prometheus
            Grafana