mindmap
    root((Key Metrics))
        Speed
            Deployment Frequency
            Lead Time
        Quality
            Change Failure Rate
            Time to Restore
        Performance
            Uptime
            Response Time