graph TB
    Big_Data((Big Data)) --> Volume[Volume<br/>Scale]
    Big_Data --> Velocity[Velocity<br/>Speed]
    Big_Data --> Variety[Variety<br/>Types]
    Big_Data --> Veracity[Veracity<br/>Quality]
    Big_Data --> Value[Value<br/>Worth]