graph LR
    A[Locality Levels] --> B[Process Local]
    A --> C[Node Local]
    A --> D[Rack Local]
    A --> E[Any]
    style B fill:#96f
    style C fill:#9cf
    style D fill:#ccf
    style E fill:#fcf