graph TD
    Size[Cluster Sizing] --> Nodes[Number of Nodes]
    Size --> Cores[Cores per Node]
    Size --> Mem[Memory per Node]
    Size --> Disk[Storage per Node]
    
    Nodes --> Load[Workload]
    Cores --> Parallel[Parallelism]
    Mem --> Cache[Caching]
    Disk --> Data[Data Size]