graph TD
    Scaling[Redis Scaling Approaches] --> VerticalM[Master-Replica<br>Vertical Scaling]
    Scaling --> ClientS[Client-Side<br>Partitioning]
    Scaling --> ProxyS[Proxy-Based<br>Partitioning]
    Scaling --> RedisC[Redis Cluster<br>Server-Side Partitioning]

    VerticalM --> MRRead[Read Scaling]
    VerticalM --> MRFailover[Failover]

    ClientS --> CHash[Client Hash]
    ClientS --> CShard[Client Sharding]

    ProxyS --> Twemproxy[Twemproxy]
    ProxyS --> Envoy[Envoy]

    RedisC --> Native[Native Cluster]
    RedisC --> Enterprise[Redis Enterprise]