graph TD
    subgraph "Master-Replica Setup"
        M[Master] --> R1[Replica 1]
        M --> R2[Replica 2]
        M --> R3[Replica 3]
    end

    CW[Client<br>Writes] --> M
    CR1[Client<br>Reads] --> R1
    CR2[Client<br>Reads] --> R2
    CR3[Client<br>Reads] --> R3